version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - |
        if [ -f dockerfile ] || [ -f Dockerfile ]; then
          aws ecr get-login-password --region <aws_region> | docker login --username AWS --password-stdin <access_id>.dkr.ecr.<aws_region>.amazonaws.com
        fi
      - echo " End Pre Build "
  build:
    commands:
      - |
        if [ -f dockerfile ] || [ -f Dockerfile ]; then
          docker build -t <ecr_name> .
          docker tag <ecr_name>:latest <access_id>.dkr.ecr.<aws_region>.amazonaws.com/<ecr_name>:latest
        fi
      - python -m py_compile app.py
      - echo " End build "
  post_build:
    commands:
      - |
        if [ -f dockerfile] || [ -f Dockerfile ]; then
          docker push <access_id>.dkr.ecr.<aws_region>.amazonaws.com/<ecr_name>:latest
        fi
      - echo " End Post Build "
artifacts:
  files:
    - '**/*'